### PR TITLE
[feat] - add CI for docker autobuild

### PR DESCRIPTION
**Pull request by Mon-ius**
add Github Action CI automatic docker image build

### CODE REVIEW

**Comment by LinB203** [comment]
Hi, thank you for your attention. We have changed the installation format of requirements to pip install -e., We apologize for any inconvenience caused.

**Comment by Mon-ius** [comment]
Hi, @LinB203

I submitted a GitHub CI workflow designed to expedite the future development and testing phases of the Open-Sora Project. It can lay the groundwork for establishing an automated training workflow build. Such an enhancement will be instrumental for the incoming PRs related to the new `Encoder` and `Decoder` architecture, allowing to assess the advancements effectively.  

If you have any question feel free to discuss with me. 🤗

**Comment by Mon-ius** [comment]
Hi @LinB203

Just got noticed that this PR has been merged. 

To enable the `functionality`, the `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` should be set up inside the setting of this repo.

The `DOCKERHUB_USERNAME` is the Docker Hub account name that can be registered from `https://hub.docker.com`;

And the `DOCKERHUB_TOKEN` can be setup via  `New Access Token` of `https://hub.docker.com/settings/security` 🤗

**Comment by LinB203** [comment]
> 你好@LinB203
> 
> 刚刚注意到这个 PR 已经被合并了。
> 
> 要启用`functionality`，应在此存储库的设置中设置`DOCKERHUB_USERNAME`和。`DOCKERHUB_TOKEN`
> 
> 是`DOCKERHUB_USERNAME`可以从 注册的 Docker Hub 帐户名`https://hub.docker.com`；
> 
> 并且可以通过🤗`DOCKERHUB_TOKEN`设置 `New Access Token``https://hub.docker.com/settings/security`

Thank you for your reminder.

**Pull request merged**
